### ISSUE TITLE
[Gamedata Issue] Incorrect linux signature for CGameClient::FileReceived

### ISSUE THREAD

**Issue by saxybois** [Batfoxkid/File-Network#2]
Hi! Every time I tried to load plugin, it gave me error "[Gamedata] Could not find CGameClient::FileReceived". Found out that problem was in linux signature 
https://github.com/Batfoxkid/File-Network/blob/8e8b3858449d9730d6e5768b818aafbf58e2d8ac/gamedata/filenetwork.txt#L60

I was looking for the correct signature in IDA and found it: **_ZN11CGameClient12FileReceivedEPKcj** (maybe you accidentally typed another _Z_)

After changing it to the found one plugin started working without any problems.

**Comment by Batfoxkid** [comment]
Ah, you can also send a Pull Request if you wish.
