### ISSUE TITLE
Gamedata issue on linux

### ISSUE THREAD

**Issue by Silorak** [Batfoxkid/File-Network#8]
Linux Ubuntu 20.04
Game: TF2

L 04/22/2023 - 00:21:18: [filenetwork.smx] [Gamedata] Could not find CGameClient::FileReceived
L 04/22/2023 - 00:21:18: [SM] Exception reported: Gamedata failed, see error logs
L 04/22/2023 - 00:21:18: [SM] Blaming: filenetwork.smx
L 04/22/2023 - 00:21:18: [SM] Call stack trace:
L 04/22/2023 - 00:21:18: [SM]   [0] ThrowError
L 04/22/2023 - 00:21:18: [SM]   [1] Line 197, c:\Users\Ryuu\Desktop\plugings\File-Network-main\scripting\filenetwork.sp::OnPluginStart

Oh yeah, since there's no way to report this forks "https://github.com/Nolo001-Aha/File-Network" issue. I am posting here.

**Comment by Nolo001-Aha** [comment]
Thanks for pointing out the unavailable Issues tab.

You may download the latest version of File Network gamedata from my repo, it should be correct.

**Comment by artvin01** [comment]
This is now fixed, sorry for the late reponse.
